name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '16' # Ensure you specify the Node.js version you need

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build project
        run: npm run build
        working-directory: ./client

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./client/dist
